
# Configuración de MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/besalud
spring.data.mongodb.database=besalud
spring.data.mongodb.auto-index-creation=true

# Configuración de Sesión
server.servlet.session.timeout=45m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.tracking-modes=COOKIE

# Verbose errors for debugging
server.error.include-message=always
server.error.include-stacktrace=always
spring.thymeleaf.cache=false
